import { GlobalCategory, GlobalSubcategory, ChatMessage, SubcategoryId } from './types';

export const GLOBAL_CATEGORIES: GlobalCategory[] = [
  {
    id: 'mobile',
    name: 'Mobile',
    subtitle: 'iPhone & Android',
    iconName: 'Smartphone',
    subcategories: [
      {
        id: 'iphone',
        name: 'iPhone',
        categoryId: 'mobile',
        memberCount: '4,850',
        onlineCount: '620',
        description: 'iOS ekosistemi, yeniliklər, tətbiqlər və Apple cihaz müzakirələri',
        iconName: 'Apple',
        accentColor: '#3b82f6',
      },
      {
        id: 'android',
        name: 'Android',
        categoryId: 'mobile',
        memberCount: '6,420',
        onlineCount: '890',
        description: 'Android sistemi, One UI, Pixel, optimizasiya və tətbiqlər',
        iconName: 'Smartphone',
        accentColor: '#10b981',
      },
    ],
  },
  {
    id: 'desktop',
    name: 'Desktop',
    subtitle: 'Windows, macOS & Linux',
    iconName: 'Monitor',
    subcategories: [
      {
        id: 'windows',
        name: 'Windows',
        categoryId: 'desktop',
        memberCount: '3,920',
        onlineCount: '410',
        description: 'Windows 11/10 proqramlar, optimizasiya, oyun və texniki dəstək',
        iconName: 'Monitor',
        accentColor: '#0ea5e9',
      },
      {
        id: 'macos',
        name: 'macOS',
        categoryId: 'desktop',
        memberCount: '3,150',
        onlineCount: '350',
        description: 'MacBook, iMac, Apple Silicon, proqramlaşdırma və iş mühiti',
        iconName: 'Laptop',
        accentColor: '#8b5cf6',
      },
      {
        id: 'linux',
        name: 'Linux',
        categoryId: 'desktop',
        memberCount: '2,480',
        onlineCount: '280',
        description: 'Distrolar, terminal əmrləri, serverlər, Docker və açıq mənbə',
        iconName: 'Terminal',
        accentColor: '#f59e0b',
      },
    ],
  },
];

export const INITIAL_SUBCATEGORY_MESSAGES: Record<SubcategoryId, ChatMessage[]> = {
  iphone: [
    {
      id: 'iph_1',
      senderId: 'user_aylin',
      senderName: 'Aylin Qədirova',
      senderColor: '#3b82f6',
      senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Salam hər kəsə! iOS 18-in batareya performansı 15 Pro-da necədir? Yeniləməyə dəyər?',
      time: '14:20',
    },
    {
      id: 'iph_2',
      senderId: 'user_elmir',
      senderName: 'Elmir Nəcəfov',
      senderColor: '#10b981',
      senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Məndə 15 Pro-dur, təxminən 8 saat aktiv ekran vaxtı verir. Heç bir qızma müşahidə etmədim, çox stabildir.',
      time: '14:24',
    },
    {
      id: 'iph_3',
      senderId: 'user_nigar',
      senderName: 'Nigar Məmmədova',
      senderColor: '#ec4899',
      senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Yeni Control Center-in fərdiləşdirilməsi və tətbiqləri gizlətmə xüsusiyyəti çox rahatdır 📱✨',
      time: '14:28',
    },
    {
      id: 'iph_4',
      senderId: 'user_murad',
      senderName: 'Murad Səfərli',
      senderColor: '#f59e0b',
      senderAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Kamera parametrlərində ProRes LOG çəkilişini yoxlayan olub? Rəng korreksiyasında böyük üstünlük verir.',
      time: '14:35',
    },
  ],
  android: [
    {
      id: 'and_1',
      senderId: 'user_kamran',
      senderName: 'Kamran Babayev',
      senderColor: '#10b981',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Samsung One UI 7 yenilənməsini gözləyənlər var? Yeni animasiyalar və bildiriş paneli çox axıcı görünür.',
      time: '15:10',
    },
    {
      id: 'and_2',
      senderId: 'user_leyla',
      senderName: 'Leyla Rüstəmova',
      senderColor: '#8b5cf6',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Pixel 9 Pro istifadə edirəm, Google-un süni intellekt və foto emalı funksiyaları inanılmaz dərəcədə güclüdür ⚡',
      time: '15:14',
    },
    {
      id: 'and_3',
      senderId: 'user_vuqar',
      senderName: 'Vüqar Əliyev',
      senderColor: '#0ea5e9',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Batareyanı qorumaq üçün doldurmanı 80%-də məhdudlaşdıran rejimi hamıya məsləhət görürəm, batareyanın deqradasiyasını xeyli azaldır.',
      time: '15:22',
    },
    {
      id: 'and_4',
      senderId: 'user_farid',
      senderName: 'Fərid Mirzəyev',
      senderColor: '#f97316',
      senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Əlavə olaraq Good Lock modulları ilə interfeysi istədiyiniz kimi dizayn edə bilərsiniz, Android-in ən böyük üstünlüyü məhz budur.',
      time: '15:30',
    },
  ],
  windows: [
    {
      id: 'win_1',
      senderId: 'user_tural',
      senderName: 'Tural Kərimli',
      senderColor: '#0ea5e9',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Windows 11 24H2 versiyasında oyun və render performansında artım hiss edən olub?',
      time: '11:05',
    },
    {
      id: 'win_2',
      senderId: 'user_rashad',
      senderName: 'Rəşad Həsənov',
      senderColor: '#10b981',
      senderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'WSL2 (Windows Subsystem for Linux) ilə proqramlaşdırma edirəm, son yeniləmələrlə yaddaş istifadəsi çox yaxşı optimallaşdırılıb.',
      time: '11:15',
    },
    {
      id: 'win_3',
      senderId: 'user_zaur',
      senderName: 'Zaur Bağırov',
      senderColor: '#6366f1',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Microsoft PowerToys mütləq qurulmalıdır! FancyZones ilə monitoru istənilən hissələrə bölmək çox asandır 🖥️',
      time: '11:24',
    },
  ],
  macos: [
    {
      id: 'mac_1',
      senderId: 'user_samir',
      senderName: 'Samir Əhmədov',
      senderColor: '#8b5cf6',
      senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Salam dostlar! M3 MacBook üçün 4K Type-C monitor məsləhəti olan varmı?',
      time: '12:30',
    },
    {
      id: 'mac_2',
      senderId: 'user_gulnar',
      senderName: 'Gülnar Mirzəyeva',
      senderColor: '#ec4899',
      senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Dell UltraSharp 27" 4K USB-C mükəmməldir, həm də Mac-i 90W ilə şarj edir, tək kabellə hər şey həll olunur 🔌',
      time: '12:36',
    },
    {
      id: 'mac_3',
      senderId: 'user_orxan',
      senderName: 'Orxan Dadaşov',
      senderColor: '#10b981',
      senderAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Spotlight əvəzinə Raycast tətbiqini mütləq yoxlayın, pəncərə idarəsi, kalkulyator və qısayollar inanılmaz rahatdır.',
      time: '12:44',
    },
  ],
  linux: [
    {
      id: 'lin_1',
      senderId: 'user_nicat',
      senderName: 'Nicat Məmmədov',
      senderColor: '#f59e0b',
      senderAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Gündəlik developer işləri üçün Fedora yoxsa Arch Linux daha uyğundur?',
      time: '16:02',
    },
    {
      id: 'lin_2',
      senderId: 'user_ilkin',
      senderName: 'İlkin Qasımov',
      senderColor: '#0ea5e9',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Fedora həm sabitdir, həm də ən yeni GNOME və paketləri gətirir. İş maşını üçün əla seçimdir 🐧',
      time: '16:11',
    },
    {
      id: 'lin_3',
      senderId: 'user_rauf',
      senderName: 'Rauf Sadıxov',
      senderColor: '#10b981',
      senderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
      isOutgoing: false,
      text: 'Server mühitində isə Docker + Ubuntu LTS və ya Debian ən etibarlı tandemdir, illərdir fasiləsiz işləyir.',
      time: '16:20',
    },
  ],
};
