import { ChatConversation } from './types';

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  // 1. Elvin (from Image 1)
  {
    id: 'chat_elvin',
    name: 'Elvin',
    avatarType: 'photo',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastMessage: 'Salam necəsən',
    lastMessageTime: '17:45',
    lastMessageStatus: 'sent',
    lastMessageType: 'text',
    category: 'direct',
    isOnline: false,
    subtitle: 'Son görülmə bu gün 17:40',
    messages: [
      {
        id: 'elv_1',
        senderId: 'elvin',
        senderName: 'Elvin',
        isOutgoing: false,
        text: 'Salam, işlər necə gedir?',
        time: '17:40',
      },
      {
        id: 'elv_2',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Salam necəsən',
        time: '17:45',
        status: 'sent',
      },
    ],
  },

  // 2. Ayhan (from Image 1)
  {
    id: 'chat_ayhan',
    name: 'Ayhan',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#bfe3f7] text-[#006699]',
    lastMessage: 'Salam necəsən',
    lastMessageTime: '17:30',
    lastMessageStatus: 'delivered',
    lastMessageType: 'text',
    category: 'direct',
    messages: [
      {
        id: 'ayh_1',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Salam necəsən',
        time: '17:30',
        status: 'delivered',
      },
    ],
  },

  // 3. Məhəmməd (from Image 1)
  {
    id: 'chat_mohammed',
    name: 'Məhəmməd',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#f8c1c4] text-[#a03038]',
    lastMessage: 'Salam necəsən',
    lastMessageTime: '17:20',
    lastMessageStatus: 'read',
    lastMessageType: 'text',
    category: 'direct',
    messages: [
      {
        id: 'moh_1',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Salam necəsən',
        time: '17:20',
        status: 'read',
      },
    ],
  },

  // 4. Fərid (from Image 1) - Unread 1
  {
    id: 'chat_farid',
    name: 'Fərid',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#b8f0ba] text-[#1c7a22]',
    lastMessage: 'Salam necəsən',
    lastMessageTime: '17:12',
    unreadCount: 1,
    lastMessageType: 'text',
    category: 'direct',
    isOnline: true,
    messages: [
      {
        id: 'far_1',
        senderId: 'farid',
        senderName: 'Fərid',
        isOutgoing: false,
        text: 'Salam necəsən',
        time: '17:12',
      },
    ],
  },

  // 5. Zaur (from Image 1) - Image, Unread 1
  {
    id: 'chat_zaur',
    name: 'Zaur',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#cbd5f5] text-[#334ea0]',
    lastMessage: 'Şəkil',
    lastMessageTime: '16:23',
    unreadCount: 1,
    lastMessageType: 'image',
    category: 'direct',
    messages: [
      {
        id: 'zau_1',
        senderId: 'zaur',
        senderName: 'Zaur',
        isOutgoing: false,
        text: 'Şəkil göndərdim, baxarsan',
        type: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
        time: '16:23',
      },
    ],
  },

  // 6. Faiq (from Image 1) - Video, Unread 1
  {
    id: 'chat_faiq',
    name: 'Faiq',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#e9eec0] text-[#717b1b]',
    lastMessage: 'video',
    lastMessageTime: '13:33',
    unreadCount: 1,
    lastMessageType: 'video',
    category: 'direct',
    messages: [
      {
        id: 'fai_1',
        senderId: 'faiq',
        senderName: 'Faiq',
        isOutgoing: false,
        text: 'Yeni video layihəsini hazırladım',
        type: 'video',
        time: '13:33',
      },
    ],
  },

  // 7. Mama (from Image 2) - Exact conversation match
  {
    id: 'chat_mama',
    name: 'Mama',
    avatarType: 'initial',
    initial: 'M',
    avatarBgColor: 'bg-[#d0e5fb] text-[#1c64b3]',
    lastMessage: 'Yaxşı ol',
    lastMessageTime: '21:06',
    lastMessageStatus: 'read',
    lastMessageType: 'text',
    category: 'direct',
    isOnline: true,
    messages: [
      {
        id: 'mam_1',
        senderId: 'mama',
        senderName: 'Mama',
        isOutgoing: false,
        text: 'Salam necəsən',
        time: '21:04',
      },
      {
        id: 'mam_2',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Salam sağol sen necəcən',
        time: '21:05',
        status: 'read',
      },
      {
        id: 'mam_3',
        senderId: 'mama',
        senderName: 'Mama',
        isOutgoing: false,
        text: 'Mende yaxşıyam',
        time: '21:06',
        replyTo: {
          id: 'mam_2',
          senderName: 'Siz',
          text: 'Salam sağol sen necəcən',
        },
      },
      {
        id: 'mam_4',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Yaxşı ol',
        time: '21:06',
        status: 'read',
        replyTo: {
          id: 'mam_3',
          senderName: 'Mama',
          text: 'Mende yaxşıyam',
        },
      },
    ],
  },

  // 8. Aqalar (from Image 3) - Group Chat with Voice notes & colored names
  {
    id: 'chat_aqalar',
    name: 'Aqalar',
    subtitle: 'Anar, Elşen, Əmrah, Fərid, Ruslan,...',
    avatarType: 'icon',
    avatarBgColor: 'bg-[#ddd1f8] text-[#5527a0]',
    lastMessage: 'Панах: Pulları hesabladız?',
    lastMessageTime: '21:32',
    unreadCount: 3,
    category: 'group',
    members: ['Панах', 'Elşen', 'Anar', 'Əmrah', 'Fərid', 'Ruslan', 'Siz'],
    messages: [
      {
        id: 'aq_1',
        senderId: 'panah',
        senderName: 'Панах',
        senderColor: '#e65100', // orange
        senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        type: 'voice',
        voiceDuration: '0:06',
        voiceDurationSec: 6,
        time: '11:17',
      },
      {
        id: 'aq_2',
        senderId: 'elshen',
        senderName: 'Elşen',
        senderColor: '#303f9f', // dark blue/indigo
        senderAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        text: '10 m siqaret alçasam piyve',
        time: '11:18',
      },
      {
        id: 'aq_3',
        senderId: 'panah',
        senderName: 'Панах',
        senderColor: '#e65100',
        senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        type: 'voice',
        voiceDuration: '0:02',
        voiceDurationSec: 2,
        time: '11:19',
      },
      {
        id: 'aq_4',
        senderId: 'elshen',
        senderName: 'Elşen',
        senderColor: '#303f9f',
        senderAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        type: 'voice',
        voiceDuration: '0:09',
        voiceDurationSec: 9,
        time: '11:20',
      },
      {
        id: 'aq_5',
        senderId: 'panah',
        senderName: 'Панах',
        senderColor: '#e65100',
        senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        text: 'Hesablayın elyb axsam deyersız',
        time: '11:21',
      },
      {
        id: 'aq_6',
        senderId: 'elshen',
        senderName: 'Elşen',
        senderColor: '#303f9f',
        senderAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        text: 'Sekileri atin daa',
        time: '21:31',
      },
      {
        id: 'aq_7',
        senderId: 'panah',
        senderName: 'Панах',
        senderColor: '#e65100',
        senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
        isOutgoing: false,
        text: 'Ülvi gelib işden?',
        time: '21:31',
      },
      {
        id: 'aq_8',
        senderId: 'me',
        senderName: 'Siz',
        isOutgoing: true,
        text: 'Pulları hesabladız?',
        time: '21:32',
        status: 'read',
      },
      {
        id: 'aq_9',
        senderId: 'other',
        senderName: 'İsmayıl',
        senderColor: '#00796b', // teal
        isOutgoing: false,
        text: 'İsmayıldadı qrupa sal atsın',
        time: '21:32',
        replyTo: {
          id: 'aq_6',
          senderName: 'Elşen',
          text: 'Sekileri atin daa',
        },
      },
      {
        id: 'aq_10',
        senderId: 'elshen',
        senderName: 'Elşen',
        senderColor: '#303f9f',
        isOutgoing: false,
        text: 'Yo',
        time: '21:32',
        replyTo: {
          id: 'aq_8',
          senderName: 'Панах',
          text: 'Pulları hesabladız?',
        },
      },
    ],
  },

  // 9. İstək (Request item for "İstəklər" tab - badge 1)
  {
    id: 'chat_request_1',
    name: 'Rəşad Qasımov',
    avatarType: 'icon',
    avatarBgColor: 'bg-amber-100 text-amber-800',
    lastMessage: 'Salam, profilinizi bəyəndim, əlaqə saxlaya bilərik?',
    lastMessageTime: 'Dünən',
    unreadCount: 1,
    category: 'request',
    messages: [
      {
        id: 'req_1',
        senderId: 'reshad',
        senderName: 'Rəşad Qasımov',
        isOutgoing: false,
        text: 'Salam, profilinizi bəyəndim, əlaqə saxlaya bilərik?',
        time: 'Dünən 19:40',
      },
    ],
  },

  // 10. İkinci İstək
  {
    id: 'chat_request_2',
    name: 'Nərmin Məmmədli',
    avatarType: 'photo',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    lastMessage: 'Salam, yeni dizayn layihəsi üzrə əməkdaşlıq etmək istərdim.',
    lastMessageTime: '14:15',
    unreadCount: 1,
    category: 'request',
    subtitle: 'Son görülmə bu gün 15:00',
    messages: [
      {
        id: 'req_2_1',
        senderId: 'narmin',
        senderName: 'Nərmin Məmmədli',
        isOutgoing: false,
        text: 'Salam, yeni dizayn layihəsi üzrə əməkdaşlıq etmək istərdim.',
        time: '14:15',
      },
    ],
  },

  // 11. İkinci Qrup ("Qruplar" tab - badge 2 alongside Aqalar)
  {
    id: 'chat_dizaynerler',
    name: 'Dizaynerlər Klubu',
    subtitle: 'Murad, Leyla, Emil, Tural...',
    avatarType: 'icon',
    avatarBgColor: 'bg-emerald-100 text-emerald-800',
    lastMessage: 'Emil: Yeni Figma komponentləri yükləndi',
    lastMessageTime: '09:15',
    category: 'group',
    members: ['Murad', 'Leyla', 'Emil', 'Tural', 'Siz'],
    messages: [
      {
        id: 'diz_1',
        senderId: 'emil',
        senderName: 'Emil',
        senderColor: '#2e7d32',
        isOutgoing: false,
        text: 'Yeni Figma komponentləri yükləndi, yoxlaya bilərsiniz.',
        time: '09:15',
      },
    ],
  },
];

export const INITIAL_GLOBAL_MESSAGES = [
  {
    id: 'glob_1',
    senderId: 'user_tural',
    senderName: 'Tural Əliyev',
    senderColor: '#303f9f',
    isOutgoing: false,
    text: 'Salam hər kəsə! Platformaya xoş gəlmisiniz 🚀',
    time: '10:00',
  },
  {
    id: 'glob_2',
    senderId: 'user_gunel',
    senderName: 'Günel Məmmədova',
    senderColor: '#c2185b',
    isOutgoing: false,
    text: 'Salamlar! Burada dizayn xidmətləri sifariş vermək çox rahatdır.',
    time: '10:15',
  },
  {
    id: 'glob_3',
    senderId: 'user_rashad',
    senderName: 'Rəşad Nəsirov',
    senderColor: '#e65100',
    isOutgoing: false,
    text: 'Qlobal çat vasitəsilə hamımız bir yerdə fikirlərimizi bölüşə bilirik 🔥',
    time: '10:32',
  },
];
